web:bundle exec rails server -p 8010 -b ${HOST:="127.0.0.1"} --environment ${RAILS_ENV:="production"}
worker: bundle exec sidekiq --environment ${RAILS_ENV:="production"} -C config/sidekiq.yml
release: rake db:migrate